//GET http://localhost:3001/api/persons


DELETE http://localhost:3001/api/blogs/5eafba2b756a3c472a7f66b9 HTTP/1.1

####
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWQiOiI1ZWIwMGQwMjlkNjVhNzE1M2VjYzc2NGYiLCJpYXQiOjE1ODg1OTY3NTl9.ygvxt5IAOiv-zjTQifCB8Sso4JzLVWNBDfPSR5dUlcY
 
{
    "title": "String3",
    "author": "String",
    "url": "String",
    "likes": 3
}

#####

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI1ZWIwMWFkNTI2ZmZkODIwZWY5NDRiN2QiLCJpYXQiOjE1ODg1OTk1MjZ9.eSU-_ohuSsMpYgNXhDEXiFWb3jqmno5VEK3-do9v8YE
 
{
    "title": "String3",
    "author": "String",
    "url": "String",
    "likes": 3
}

#####

DELETE http://localhost:3001/api/blogs/5eb0157fc41a5a1c3f65da35 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWQiOiI1ZWIwMGQwMjlkNjVhNzE1M2VjYzc2NGYiLCJpYXQiOjE1ODg1OTY3NTl9.ygvxt5IAOiv-zjTQifCB8Sso4JzLVWNBDfPSR5dUlcY

#####

PUT http://localhost:3001/api/blogs/5eafb9b9756a3c472a7f66b8 HTTP/1.1
content-type: application/json

{
    "likes": 7
}

####

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "test2",
    "name": "test name",
    "password": "test"
}

####
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "test2",
    "password": "test"
}

####
